# Generated by Django 3.2.9 on 2021-11-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sold',
            field=models.IntegerField(),
        ),
    ]
